# This is a basic workflow to help you get started with Actions

name: ci

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run lint
      - run: npm run build

      # publish to npm
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx 🐳
        uses: docker/setup-buildx-action@v1

      # 登陆 Docker Hub
      - name: Login Docker Hub 🐳🐳
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PSW }}

      # 打包并推送 docker 镜像
      - name: Build & Push Docker Image 🐳🐳🐳
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: shalldie/togame:latest,shalldie/togame:${{ steps.publish.outputs.version }}
